version: "3.9"
services:
  web-server:
    container_name: "web-server"
    build: ./server
    command: cargo watch -x 'run'
    depends_on:
      - postgres
    # environment: 
    # - DATABASE_URL=postgresql://docker:docker@postgres/p2boards
    # - SERVER.HOST=0.0.0.0
    # - SERVER.PORT=8080
    # - PROOF.DEMO=80
    # - PROOF.VIDEO=100
    env_file:
      ./server/.env.entrypoint.dev
    ports:
      - "8080:8080"

  postgres:
    build: ./db
    environment:
      - POSTGRES_DB=p2boards
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker