[package]
name = "server"
version = "0.1.0"
authors = ["Daniel Bates <36864021+DanielBatesJ@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
rocket_cors = "0.5.2"
futures = "0.3.17"

sqlx = { version = "0.5.7", features = [ "runtime-tokio-rustls", "postgres", "chrono"] }
chrono = { version = "0.4.19", features = ["serde", "rustc-serialize"] }

serde = "1.0.123"
serde_json = "1.0.64"
serde_derive = "1.0.123"

dotenv = "0.15.0"
config = "0.11.0"
num = "0.1.42"
env_logger = "0.8.3"
log = "0.4.14"
anyhow = "1.0.43"

steam-auth = "1.0.0"